// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnYYU3V1dLiSWyuAdysmE_CWPhcEYSzSc',
    appId: '1:77901567813:web:cfbdd44a91c84ed316502c',
    messagingSenderId: '77901567813',
    projectId: 'unloque',
    authDomain: 'unloque.firebaseapp.com',
    storageBucket: 'unloque.firebasestorage.app',
    measurementId: 'G-X08N3W6WZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhkrQjpZ02GOo_ep1Xk4x7aB9CZ4wKOUc',
    appId: '1:77901567813:android:34563810ca6350a416502c',
    messagingSenderId: '77901567813',
    projectId: 'unloque',
    storageBucket: 'unloque.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnK7r6Gs3rTDgi9zivoBqJtQlYNqU0KoA',
    appId: '1:77901567813:ios:3319fbf9b954dbd716502c',
    messagingSenderId: '77901567813',
    projectId: 'unloque',
    storageBucket: 'unloque.firebasestorage.app',
    iosBundleId: 'com.example.unloque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnK7r6Gs3rTDgi9zivoBqJtQlYNqU0KoA',
    appId: '1:77901567813:ios:3319fbf9b954dbd716502c',
    messagingSenderId: '77901567813',
    projectId: 'unloque',
    storageBucket: 'unloque.firebasestorage.app',
    iosBundleId: 'com.example.unloque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnYYU3V1dLiSWyuAdysmE_CWPhcEYSzSc',
    appId: '1:77901567813:web:d99557ba4ae6907e16502c',
    messagingSenderId: '77901567813',
    projectId: 'unloque',
    authDomain: 'unloque.firebaseapp.com',
    storageBucket: 'unloque.firebasestorage.app',
    measurementId: 'G-ENTX2Y8HDC',
  );
}
